#!/usr/bin/bash
set -euo pipefail

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 6)
bold=$(tput bold)
reset=$(tput sgr0)

dot() { "$DOTS_HOME/bin/dot" "$@"; }

_w() {
  local -r text="${1:-}"
  echo -e "$text"
}

_info()    { _w " ${bold}${green}>${reset} $1"; }
_success() { _w " ${green}✔  $1${reset}"; }
_warn()    { _w " ${yellow}${bold}! $1${reset}"; }
_error()   { _w " ${red}✖  $1${reset}"; }
_quest()   { read -rp " ${bold}${green}?${reset}${bold} $1${reset} " "$2"; }
_abort()   { _error "$1\n" && exit 1; }

command_exists() { type "$1" >/dev/null 2>&1;  }

echo
_warn "Warning: This is a personal installation script for my dotfiles. Please, don't use it without
 knowing exactly what it does and how these dotfiles work. Note that this process may break your
 system configuration and, for this reason, is strongly recommended to backup your current
 configuration before the installation. See README.md for more information.\n"

read -rp "${yellow} Do you want to continue [y/N] " cont
[[ $cont == "N" || $cont == "n" || -z $cont ]] && echo && exit 1

echo
_quest "Where do you want the dotfiles be located? (default to ~/.dots)" "DOTS_HOME"

export DOTS_HOME=${DOTS_HOME:-$HOME/.dots}
[[ -d $DOTS_HOME ]] && _abort "$DOTS_HOME already exists! Aborting..."

_info "Nice! dotfiles will be located in ${blue}$DOTS_HOME${reset}\n"

if ! command_exists git; then
  _warn "Git is not installed in your system"
  _info "Trying to install Git..."

  if command_exists apt; then
    _info "Installing Git using apt..."
    sudo apt -y install git >/dev/null 2>&1
  elif command_exists pacman; then
    _info "Installing Git using pacman..."
    sudo pacman -S --noconfirm git >/dev/null 2>&1
  elif command_exists dnf; then
    _info "Installing Git using dnf..."
    sudo dnf -y install git >/dev/null 2>&1
  else
    _abort "Could not install Git. No package manager was found :( Aborting..."
  fi
fi

_info "Cloning rixsilverith/dots into ${blue}$DOTS_HOME${reset}"
git clone --depth 1 https://github.com/rixsilverith/dots.git "$DOTS_HOME" >/dev/null 2>&1

_info "Updating Git submodules and dependencies"
git submodule update --init --recursive 2>&1

if ! command_exists zsh; then
  _warn "zsh is not installed in your system"
  _info "Installing zsh"

  ! dot package install zsh && _error "Could not install zsh :("
fi

if [[ ! $SHELL == *zsh* ]]; then
  _info "Setting zsh as the default shell"
  sudo chsh -s "$(command -v zsh)"
fi

_info "Configuring zsh. This might need you root permissions"
echo "export ZDOTDIR=$HOME/.dots/shell/zsh" | sudo tee -a /etc/zsh/zshenv > /dev/null

export ZIM_HOME=$DOTS_HOME/modules/zimfw

_info "Installing Zim"
zsh "$ZIM_HOME/zimfw.zsh" install

_info "Applying necessary symlinks"
dot symlinks apply

_success "dotfiles installed successfully!\n"
