#!/usr/bin/env bash
set -euo pipefail

source "$DOTS_HOME/scripts/core/dot.sh"

##? Apply dotfiles symlinks
##?
##? Usage: dot symlinks apply
docs::parse "$@"

symlinks::apply() {
  local -r symlinks_config="$DOTS_HOME/symlinks.yaml"
  shift
  echo
  "$DOTS_HOME/modules/dotbot/bin/dotbot" -d $DOTS_HOME -c $symlinks_config "$@"
  echo
}

symlinks::apply
