#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Extract a compressed file
##?
##? Usage: dot (filesystem | fs) extract <file>
docs::parse "$@"

source "$DOTS_HOME/scripts/core/log.sh"

file=$1

if [ -f $file ]; then
  case $file in
    *.tar.bz2) tar xvjf $file ;;
    *.tar.gz)  tar xvzf $file ;;
    *.tar)     tar xvf $file ;;
    *.rar)     unrar x $file ;;
    *.gz)      gunzip $file ;;
    *.zip)     unzip $file ;;
    *.7z)      7z x $file ;;
    *)         log::warn "Don't know how to extract ${file}..." ;;
  esac
else
  log:error "$file is not a valid file!"
fi
