#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Extracts a compressed file
##?
##? Usage: dot (filesystem|fs) extract <file>
##?
##?    Supported formats: tar.bz2, tar.gz, tar, gz, rar, zip, 7z.
##?
docs::parse "$@"

[[ $# -eq 0 ]] && dot filesystem extract -h && exit 0
file="$1"

[[ ! -f "$file" ]] && log::abort "$file isn't a file :v"

case "$file" in
  *.tar.bz2) tar xvjf "$file" ;;
  *.tar.gz)  tar xvzf "$file" ;;
  *.tar)     tar xvf "$file" ;;
  *.rar)     unrar x "$file" ;;
  *.gz)      gunzip "$file" ;;
  *.zip)     unzip "$file" ;;
  *.7z)      7z x "$file" ;;
  *)         log::info "Don't know how to extract ${file} :(" ;;
esac
