#!/usr/bin/bash
set -euo pipefail

source "$DOTS_HOME/scripts/core/dot.sh"

##? Kills a process given its name
##?
##? Usage: dot process kill <process_name>
docs::parse "$@"

process_name="$1"

ps aux |
  grep "$process_name" |
  grep -v grep |
  grep -v kill |
  awk '{print $2}' |
  xargs kill -9

log::success "Process <$process_name> killed successfully!"
