#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Kills a process given its name
##?
##? Usage: dot (process|proc) kill <process_name>
##?
docs::parse "$@"

[[ $# -eq 0 ]] && dot process kill -h && exit 0
[[ -n "$1" ]] && process_name="$1"

ps aux |
  grep "$process_name" |
  grep -v grep |
  grep -v kill |
  awk '{print $2}' |
  xargs kill -9

log::success "Process <$process_name> killed successfully!"
