#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Generates a cryptographically secure password n chars long
##?
##? Usage: dot (security|sec) keygen [n]
##?
##?    The generated password contains both alphanumeric characters and
##?    and symbols, and it is automatically copied to the clipboard.
##?
docs::parse "$@"
script::depends_on xclip

num_chars=${1:-30}

# Taken from https://en.m.wikipedia.org/wiki/Random_password_generator
mkpw() {
  LC_ALL=C
  tr -dc '[:graph:]' < /dev/urandom | head -c $num_chars; echo
}

echo -n "$(mkpw)" | xclip -selection clipboard
notify-send -i "$DOTS_HOME/wm/dunst/icons/key.svg" "Key generator" "Password copied to the clipboard!"
