#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Generates a cryptographically secure password
##?
##? Usage: dot (security | sec) keygen
docs::parse "$@"

num_chars=30

# Taken from https://en.m.wikipedia.org/wiki/Random_password_generator
mkpw() {
  LC_ALL=C
  tr -dc '[:graph:]' < /dev/urandom | head -c ${1:-$num_chars}; echo
}

echo $(mkpw) | xclip -selection clipboard

log::info "Password copied to the clipboard!"
