#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Benchmark Zsh shell spawning time
##?
##? Usage: dot (shell | sh) test-performance
docs::parse "$@"

hyperfine '/bin/zsh -i -c exit' --warmup 1

echo -e "Zsh info: /bin/zsh - $(/bin/zsh --version)\n"
