#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/lib.sh"

##? Zsh helpers and utilities
##?
##? usage: doit (shell|sh) zsh (benchmark|optimize)
##?
##?    Some helper functions to benchmark and optimize zsh.
##?
docs::parse "$@"
script::depends_on hyperfine

zsh::benchmark() {
  hyperfine '/bin/zsh -i -c exit' '/usr/bin/zsh -i -c exit' --warmup 1
  echo -e "Currently using $(tput setaf 3)$(command -v zsh)$(tput sgr0) - $(/bin/zsh --version)\n"
}

zsh::optimize() {
  find "$DOTS_HOME/shell/zsh" -name '*.zwc' -exec rm -rf {} \;
  find "$DOTS_HOME/shell/zsh" -name '*.old' -exec rm -rf {} \;
  find "$DOTS_HOME/modules/zimfw" -name '*.zwc' -exec rm -rf {} \;
  find "$DOTS_HOME/modules/zimfw" -name '*.old' -exec rm -rf {} \;

  zsh -c "source ${ZDOTDIR:-${DOTS_HOME}/shell/zsh}/.zlogin"
}

[[ $# -eq 0 ]] && doit shell zsh -h && exit 0

cmd=$1
case "$cmd" in
  "benchmark") zsh::benchmark ;;
  "optimize") zsh::optimize ;;
  *) doit shell zsh -h ;;
esac
