#!/bin/sh

# truncate a couple of common commands used here
_bc() { bspc config "$@"; }
_br() { bspc rule "$@"; }

pgrep -x sxhkd > /dev/null || sxhkd -c "$DOTS_HOME/os/bspwm/keybinds" &
"$DOTS_HOME/os/polybar/launch.sh" &

bspc monitor -d I II III IV V VI VII VIII

_bc border_width         0
_bc window_gap          12

_bc split_ratio          0.52
_bc borderless_monocle   true
_bc gapless_monocle      true

_br -a Zathura state=tiled
_br -a firefox desktop='^2' followon=on
_br -a discord desktop='^3' followon=on
