#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/lib.sh"

##? Clean caches, empty trash, remove dead symlinks and empty dirs
##?
##? usage: doit (system|sys) clean
##?
##?    Requires root priviledge in order to perform a full clean up.
##?
docs::parse "$@"

set +e # prevent the script from crashing if there is some error

# authenticate user and refresh cached credentials for the rest of the script
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2> /dev/null &

log::info "Removing empty directories and files"
fd . $HOME --type empty --exclude .git --exec rm -rf

log::info "Purging directories that no longer exist from fre"
fre --sorted | while read dir; do if [ ! -d "$dir" ]; then fre --delete "$dir"; fi; done

log::info "Cleaning cached versions of uninstalled packages with pacman"
sudo paccache -ruk0 > /dev/null

log::info "Removing orphan packages from the system"
pacman -Qtdq | sudo pacman -Rns --noconfirm - &> /dev/null

log::info "Removing broken symlinks"
fd . $HOME --hidden --follow --type symlink --exec rm -rf

log::info "Cleaning zsh cache"
doit shell zsh optimize &> /dev/null

log::success "Clean up done!"

