#!/usr/bin/bash
set -euo pipefail

##? Cleans useless files such as cache, empties trash, etc.

source "$DOTS_HOME/scripts/core/log.sh"

if ! has gio; then
  i=$(feedback::confirmation "This script uses the gio command. Wanna install it?")
  [[ i -ne 0 ]] && log::abort "Aborting..."

  log::info "Installing glib2"
  sudo pacman -S --noconfirm glib2
fi

gio trash --empty

