#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Use redshift to enable/disable blue screen light reduction
##?
##? Usage: dot (system | sys) night-shift <on|off|toggle>
docs::parse "$@"

# To track whether or not the night mode is enabled, we'll create
# the DOTS_NIGHT_SHIFT_FILE file in the redshift directory when night
# mode is enabled and delete it when it's disabled. This way is
# pretty easy for other scripts (mainly a custom Qtile widget) to
# know if night mode is enabled.
#
# By using this approach only one key bind is needed to toggle night
# mode instead of two.
DOTS_NIGHT_SHIFT_FILE="$DOTS_HOME/util/redshift/.night-shift-enabled"

temp=3700

enable_night_shift() {
  local -r t="$1"
  redshift -O $t
  touch $DOTS_NIGHT_SHIFT_FILE
  notify-send "Night shift enabled!"
}

disable_night_shift() {
  redshift -x
  rm -f $DOTS_NIGHT_SHIFT_FILE
  notify-send "Night shift disabled!"
}

toggle_night_shift() {
  if [[ -f $DOTS_NIGHT_SHIFT_FILE ]]; then
    disable_night_shift
  else
    enable_night_shift $temp
  fi
}

[[ $# -lt 1 ]] && log::abort "Wrong number of arguments"

case "$1" in
  "on")     enable_night_shift $temp ;;
  "off")    disable_night_shift ;;
  "toggle") toggle_night_shift ;;
  *)        log::abort "Wrong arguments" ;;
esac
