#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/lib.sh"

##? Symlink as specified in `$DOTS_HOME/misc/symlinks.csv`
##?
##? usage: doit self link
##?
##?    Note to self: this script may overwrite some files, so just... be
##?    careful... I guess. Used by `doit self install`.
##?
docs::parse "$@"

while IFS=", " read -r dotfolder origin; do
  [[ -d "$origin" && ! -L "$origin" ]] && rm -rf "$origin"
  [[ -L "$origin" && "$(readlink "$origin")" == "$dotfolder" ]] && continue

  ln -sf "$dotfolder" "$origin"
  [[ $? -ne 0 ]] && echo -e "\033[1;31mError\033[0m creating symlink \033[1;36m$origin --> $dotfolder\033[0m"
done < <(envsubst < "$DOTS_HOME/misc/symlinks.csv")

# By default, "read" does not expand variables. That "envsubst" thing
# makes it so variables read from the file are expanded.
# See: https://askubuntu.com/questions/974257/read-string-with-user-variable-as-text-and-resolve-it
