#!/usr/bin/bash
set -euo pipefail

##? Check for updates and sync the dotfiles

source "$DOTS_HOME/scripts/core/log.sh"

project_status() {
    cd "$DOTS_HOME" || exit

    local -r UPSTREAM="master"
    local -r LOCAL=$(git rev-parse @)
    local -r REMOTE=$(git rev-parse "$UPSTREAM")
    local -r BASE=$(git merge-base @ "$UPSTREAM")

    if [[ "$LOCAL" == "$REMOTE" ]]; then
        echo "synced"
    elif [[ "$LOCAL" == "$BASE" ]]; then
        echo "behind"
    elif [[ "$REMOTE" == "$BASE" ]]; then
        echo "ahead"
    else
        echo "diverged"
    fi
}

self_update() {
    cd "$DOTS_HOME" || exit

    _info "Checking for updates..."

    git fetch
    if [[ $(project_status) == "behind" ]]; then
        i=$(feedback::confirmation "A new version of the dotfiles is available! Wanna clone it?")
        if [[ $i -eq 0 ]]; then
            _info "Pulling from GitHub..."
            git pull >/dev/null 2>&1 && exit 0 || _error "Failed to pull from GitHub"
        else
            exit 1
        fi
    elif [[ $(project_status) == "ahead" ]]; then
        _info "Your dotfiles are ahead of the repo. Push changes ;)"
    else
        _info $(project_status)
        _success "Your dotfiles are up to date :)"
        echo
        exit 0
    fi
}

echo
self_update
