#!/usr/bin/bash
set -euo pipefail

source "$DOTS_HOME/scripts/core/dot.sh"

##? Check for updates and sync the dotfiles
##?
##? Usage: dot self update
docs::parse "$@"

dotfiles_status() {
  cd "$DOTS_HOME" || exit

  local -r UPSTREAM="master"
  local -r LOCAL=$(git rev-parse @)
  local -r REMOTE=$(git rev-parse "$UPSTREAM")
  local -r BASE=$(git merge-base @ "$UPSTREAM")

  if [[ "$LOCAL" == "$REMOTE" ]]; then
    echo "synced"
  elif [[ "$LOCAL" == "$BASE" ]]; then
    echo "behind"
  elif [[ "$REMOTE" == "$BASE" ]]; then
    echo "ahead"
  else
    echo "diverged"
  fi
}

echo
cd "$DOTS_HOME" || exit

log::info "Checking for updates"

git fetch
if [[ $(dotfiles_status) == "behind" ]]; then
  res=$(feedback::confirmation "A new version of the dotfiles is available! Wanna clone it?")

  if [[ $res -eq 0 ]]; then
    log::info "Pulling from GitHub"
    git pull >/dev/null 2>&1 && exit 0 || log::error "Failed to pull from GitHub"
  else
    exit 1
  fi
elif [[ $(dotfiles_status) == "ahead" ]]; then
  log::info "Your dotfiles are ahead of the repo. Push!"
else
  log::success "Your dotfiles are up to date :)"
  echo
  exit 0
fi

echo

