#!/usr/bin/bash
set -euo pipefail

source "$DOTS_HOME/scripts/core/dot.sh"

##? Display a list of the available ANSI colors
##?
##? Usage: dot ui colors
docs::parse "$@"

zsh -c 'for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%12)):#3}:+"\n"}; done'
#for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
