#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Change wallpaper given its name
##?
##? Usage: dot ui wall <name>
docs::parse "$@"

walls_dir="$DOTS_HOME/misc/walls"

list_walls() {
  local -r walls=($(fd . $walls_dir --extension jpg))
  for wall in ${walls[@]}; do
    name=${wall%.jpg}
    name=${name##*/}
    echo $name
  done
  exit 0
}

set_wall() {
  cp $walls_dir/${1}.jpg $walls_dir/.wall.jpg
  feh --bg-scale --no-fehbg $walls_dir/.wall.jpg

  notify-send "Background" "Background changed to <b>${1}</b>!"
}

[[ $# -eq 0 ]] && list_walls

wall_name="$1"
shift

set_wall $wall_name

