#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/lib.sh"

##? Set the workspace background image
##?
##? usage: doit ui wall [name]
##?
##?    If [name] is not provided, a list with the available walls will be
##?    displayed for one to be selected.
##?
docs::parse "$@"
# script::depends_on feh fd dmenu swaybg

walls_dir="$DOTS_HOME/misc/walls"

wall::set() {
  cp "$walls_dir/${1}.jpg" "$walls_dir/.wall.jpg"
  swaybg --image "$walls_dir/.wall.jpg" &> /dev/null &
  #feh --bg-scale --no-fehbg "$walls_dir/.wall.jpg"
  #notify-send -i "$DOTS_HOME/wm/dunst/icons/background.svg" "Background changed" "Background changed to <b>${1}</b>!"
}

wall::list() {
  local -r walls=($(fd . "$walls_dir" --extension jpg))
  declare -a wall_list

  for wall in ${walls[@]}; do
    name=${wall%.jpg}
    name=${name##*/}
    wall_list+=("${name^}")
  done

  selected=$(printf '%s\n' "${wall_list[@]}" | fzf --layout reverse-list --height 10% --cycle --pointer '➜' \
        --color 'hl:255,hl+:255,pointer:255:bold,marker:255,info:248,prompt:255,bg+:-1')
  # selected=$(printf '%s\n' "${wall_list[@]}" | dmenu -p "Choose a wall to set ")
  wall::set "${selected,,}" && exit 0
}

[[ $# -eq 0 ]] && wall::list || wall::set "$1"

