#!/bin/bash

WAYLAND_CONFIG="$HOME/.config/waybar/config $HOME/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $WAYLAND_CONFIG
    killall waybar
done
