#!/usr/bin/bash

source "$DOTS_HOME/scripts/core/dot.sh"

##? Optimizes (compresses) an image preserving the original
##?
##? Usage: dot (image|img) optimize <image>
##?
##?    <image> must be in jpeg format.
##?
docs::parse "$@"
script::depends_on jpegoptim

[[ $# -eq 0 ]] && dot image optimize -h && exit 0
filename=$1

[ -f "$filename" ] || log::abort "$filename is not a file :v"

orig_file=$(echo "$filename" | sed 's/\(.*\)\./\1.original./')

cp "$filename" "$orig_file"
jpegoptim --max 85 -q "$filename"

log::success "Image $filename optimized!"
